### ISSUE TITLE
Improve Logging During Test Runs

### ISSUE THREAD

**Issue by b-vennes** [Topl/Bifrost#1132]
## Description
`sbt test` outputs a lot of logging information that can be difficult to parse test results. It would be nice to have a way to disable all logging except for errors.

## Acceptance Criteria
Some documentation or a config option for enabling quieter tests.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-844) by [Unito](https://www.unito.io)

**Comment by b-vennes** [comment]
Simple solution is `sbt "set logLevel := Level.Error" "test"`.

**Comment by SeanCheatham** [comment]
An alternative suggestion:

Copy `logback.xml` from `src/main/resources/logback.xml` to `src/test/resources/logback-test.xml` (renaming the file in the process).  Inside of the new `logback-test.xml`, you can set the root log level to something higher (like `INFO`), or you can set log levels by package, for example:

```xml
    <logger name="co.topl" level="DEBUG" />

    <root level="INFO">
        <appender-ref ref="STDOUT" />
    </root>
 ```
 
 The logback library will search for a `logback-test.xml` on the classpath first.  Since the logback-test.xml is scoped to the `src/test` directory, it won't be included in the application release; it will only be used during testing.

**Comment by jingsting** [comment]
@b-vennes Please connect with James about this ticket
